### ISSUE TITLE
Literal types

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#118]
```scala
class C {
  type T = 42
}
```

```
Test.scala:2: error: identifier expected but integer literal found
  type T = 42
           ^
Test.scala:2: error: compiler crash
  type T = 42
          ^
rsc.util.CrashException: Test.scala:2: error: identifier expected but integer literal found
  type T = 42
           ^
ExpectedToken(Position(Input(Paths.get("Test.scala")), 21, 21), 25, 43)
	at rsc.util.CrashException$.apply(CrashException.scala:15)
	at rsc.util.ErrorUtil$class.crash(ErrorUtil.scala:10)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.parse.Messages$class.crash(Messages.scala:14)
	at rsc.parse.Parser.crash(Parser.scala:10)
	at rsc.parse.Messages$class.reportOffset(Messages.scala:43)
	at rsc.parse.Parser.reportOffset(Parser.scala:10)
	at rsc.parse.Paths$class.value(Paths.scala:23)
	at rsc.parse.Paths$class.tptId(Paths.scala:41)
	at rsc.parse.Parser.tptId(Parser.scala:10)
	at rsc.parse.Paths$class.errorTptId(Paths.scala:182)
	at rsc.parse.Parser.errorTptId(Parser.scala:10)
	at rsc.parse.Paths$class.tptPath(Paths.scala:83)
	at rsc.parse.Parser.tptPath(Parser.scala:10)
	at rsc.parse.Tpts$class.simpleTpt(Tpts.scala:216)
	at rsc.parse.Parser.simpleTpt(Parser.scala:10)
	at rsc.parse.Tpts$class.annotTpt(Tpts.scala:189)
	at rsc.parse.Parser.annotTpt(Parser.scala:10)
	at rsc.parse.Tpts$class.withTpt(Tpts.scala:169)
	at rsc.parse.Tpts$class.refinedTpt(Tpts.scala:113)
	at rsc.parse.Parser.refinedTpt(Parser.scala:10)
	at rsc.parse.Tpts$class.infixTpt(Tpts.scala:78)
	at rsc.parse.Parser.infixTpt(Parser.scala:10)
	at rsc.parse.Tpts$class.tpt(Tpts.scala:53)
	at rsc.parse.Parser.tpt(Parser.scala:10)
	at rsc.parse.Defns$class.defnType(Defns.scala:113)
	at rsc.parse.Parser.defnType(Parser.scala:10)
	at rsc.parse.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:159)
	at rsc.parse.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:90)
	at rsc.parse.Helpers$class.inBraces(Helpers.scala:65)
	at rsc.parse.Parser.inBraces(Parser.scala:10)
	at rsc.parse.Templates$$anonfun$templateBraces$1.apply(Templates.scala:90)
	at rsc.parse.Templates$$anonfun$templateBraces$1.apply(Templates.scala:87)
	at rsc.parse.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.Parser.banEscapingWildcards(Parser.scala:10)
	at rsc.parse.Templates$class.templateBraces(Templates.scala:87)
	at rsc.parse.Templates$class.defnTemplate(Templates.scala:43)
	at rsc.parse.Parser.defnTemplate(Parser.scala:10)
	at rsc.parse.Defns$class.defnClass(Defns.scala:17)
	at rsc.parse.Parser.defnClass(Parser.scala:10)
	at rsc.parse.Sources$$anonfun$rsc$parse$Sources$$packageStats$1.apply(Sources.scala:71)
	at rsc.parse.Sources$$anonfun$rsc$parse$Sources$$packageStats$1.apply(Sources.scala:52)
	at rsc.parse.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.Parser.banEscapingWildcards(Parser.scala:10)
	at rsc.parse.Sources$class.rsc$parse$Sources$$packageStats(Sources.scala:52)
	at rsc.parse.Sources$$anonfun$rsc$parse$Sources$$sourceStats$1.apply(Sources.scala:47)
	at rsc.parse.Sources$$anonfun$rsc$parse$Sources$$sourceStats$1.apply(Sources.scala:17)
	at rsc.parse.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.Parser.banEscapingWildcards(Parser.scala:10)
	at rsc.parse.Sources$class.rsc$parse$Sources$$sourceStats(Sources.scala:17)
	at rsc.parse.Sources$class.source(Sources.scala:14)
	at rsc.parse.Parser.source(Parser.scala:10)
	at rsc.Compiler$$anonfun$rsc$Compiler$$parse$1.apply(Compiler.scala:97)
	at rsc.Compiler$$anonfun$rsc$Compiler$$parse$1.apply(Compiler.scala:84)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at rsc.Compiler.rsc$Compiler$$parse(Compiler.scala:84)
	at rsc.Compiler$$anonfun$tasks$1.apply$mcV$sp(Compiler.scala:75)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:34)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:31)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:31)
	at rsc.cli.Main$.run(Main.scala:21)
	at rsc.cli.Main$.main(Main.scala:11)
	at rsc.cli.Main.main(Main.scala)
```

**Comment by xeno-by** [comment]
At the moment, we support outlining final vals into vals with literal types, as well as mjaring literal types into appropriate ScalaSignatures. This is enough to cover Scala 2.12, however Scala 2.13 adds support for surface syntax for literal types (https://github.com/scala/scala/pull/5310). This is not required for our M4 work, so I'll leave this for future work.
