### ISSUE TITLE
Crash when outlining case classes with more than 22 fields

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#185]
```scala
case class C(
  x1: Int,
  x2: Int,
  x3: Int,
  x4: Int,
  x5: Int,
  x6: Int,
  x7: Int,
  x8: Int,
  x9: Int,
  x10: Int,
  x11: Int,
  x12: Int,
  x13: Int,
  x14: Int,
  x15: Int,
  x16: Int,
  x17: Int,
  x18: Int,
  x19: Int,
  x20: Int,
  x21: Int,
  x22: Int,
  x23: Int)
```

```diff
Test.scala:1: error: compiler crash
case class C(
     ^
rsc.util.CrashException: scala/runtime/AbstractFunction23#
	at rsc.util.CrashException$.apply(CrashException.scala:24)
	at rsc.util.ErrorUtil$class.crash(ErrorUtil.scala:18)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.outline.Outliner.resolveScope(Outliner.scala:402)
	at rsc.outline.Outliner.rsc$outline$Outliner$$appendParent$1(Outliner.scala:98)
	at rsc.outline.Outliner.synthesizeParents$1(Outliner.scala:126)
	at rsc.outline.Outliner.trySucceed(Outliner.scala:141)
	at rsc.outline.Outliner.apply(Outliner.scala:36)
	at rsc.outline.Outliner.apply(Outliner.scala:19)
	at rsc.Compiler.rsc$Compiler$$outline(Compiler.scala:158)
	at rsc.Compiler$$anonfun$tasks$4.apply$mcV$sp(Compiler.scala:78)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:34)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:31)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:31)
	at rsc.cli.Main$.process(Main.scala:35)
	at rsc.cli.Main$.main(Main.scala:14)
	at rsc.cli.Main.main(Main.scala)
one error found
```

**Comment by xeno-by** [comment]
Fixed in https://github.com/xeno-by/rsc/tree/topic/assorted (see a link to the commit in the ticket history above).
