### ISSUE TITLE
Crash when selecting from a with type

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#188]
```scala
trait A

trait B {
  type T
}

class D {
  def m(x: A with B): x.T = ???
}
```

```
Test.scala:8: error: compiler crash
  def m(x: A with B): x.T = ???
                      ^
rsc.util.CrashException: <_empty_/A#> with <_empty_/B#>
TptWith(List(TptId("A"), TptId("B")))
	at rsc.util.CrashException$.apply(CrashException.scala:24)
	at rsc.util.ErrorUtil$class.crash(ErrorUtil.scala:18)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.outline.Outliner.loop$4(Outliner.scala:391)
	at rsc.outline.Outliner.resolveScope(Outliner.scala:400)
	at rsc.outline.Outliner.loop$3(Outliner.scala:343)
	at rsc.outline.Outliner.apply(Outliner.scala:359)
	at rsc.outline.Outliner.rsc$outline$Outliner$$apply(Outliner.scala:257)
	at rsc.outline.Outliner.apply(Outliner.scala:234)
	at rsc.outline.Outliner.apply(Outliner.scala:20)
	at rsc.Compiler.rsc$Compiler$$outline(Compiler.scala:158)
	at rsc.Compiler$$anonfun$tasks$4.apply$mcV$sp(Compiler.scala:78)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:34)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:31)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:31)
	at rsc.cli.Main$.process(Main.scala:35)
	at rsc.cli.Main$.main(Main.scala:14)
	at rsc.cli.Main.main(Main.scala)
one error found
```

**Comment by xeno-by** [comment]
Thanks to https://github.com/twitter/rsc/pull/299, this is no longer a problem.
