### ISSUE TITLE
Cannot parse FlagsTest.scala

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#220]
I haven't come up with a good minimization, so here's the source file in its entirety: https://github.com/twitter/util/blob/d5f34617a073d183297cc78758b5c31bdfd2b3f0/util-app/src/test/scala/com/twitter/app/FlagsTest.scala

```
/Users/eburmako/Projects/source/util/util-app/src/test/scala/com/twitter/app/FlagsTest.scala:198: error: identifier expected but string literal found
        """Set flags:""",
                     ^
rsc.util.CrashException: identifier expected but string literal found
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:10)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.parse.scala.Messages$class.reportOffset(Messages.scala:39)
	at rsc.parse.scala.Parser.reportOffset(Parser.scala:13)
	at rsc.parse.scala.Paths$class.value(Paths.scala:24)
	at rsc.parse.scala.Paths$class.tptId(Paths.scala:42)
	at rsc.parse.scala.Parser.tptId(Parser.scala:13)
	at rsc.parse.scala.Paths$class.errorTptId(Paths.scala:183)
	at rsc.parse.scala.Parser.errorTptId(Parser.scala:13)
	at rsc.parse.scala.Paths$class.tptPath(Paths.scala:84)
	at rsc.parse.scala.Parser.tptPath(Parser.scala:13)
	at rsc.parse.scala.Tpts$class.simpleTpt(Tpts.scala:218)
	at rsc.parse.scala.Parser.simpleTpt(Parser.scala:13)
	at rsc.parse.scala.Tpts$class.annotTpt(Tpts.scala:191)
	at rsc.parse.scala.Parser.annotTpt(Parser.scala:13)
	at rsc.parse.scala.Tpts$class.withTpt(Tpts.scala:171)
	at rsc.parse.scala.Tpts$class.refinedTpt(Tpts.scala:115)
	at rsc.parse.scala.Parser.refinedTpt(Parser.scala:13)
	at rsc.parse.scala.Tpts$class.infixTpt(Tpts.scala:86)
	at rsc.parse.scala.Parser.infixTpt(Parser.scala:13)
	at rsc.parse.scala.Tpts$class.tpt(Tpts.scala:61)
	at rsc.parse.scala.Parser.tpt(Parser.scala:13)
	at rsc.parse.scala.Terms$class.term1(Terms.scala:174)
	at rsc.parse.scala.Parser.term1(Parser.scala:13)
	at rsc.parse.scala.Terms$$anonfun$term$1.apply(Terms.scala:40)
	at rsc.parse.scala.Terms$$anonfun$term$1.apply(Terms.scala:38)
	at rsc.parse.scala.Wildcards$class.wrapEscapingTermWildcards(Wildcards.scala:56)
	at rsc.parse.scala.Parser.wrapEscapingTermWildcards(Parser.scala:13)
	at rsc.parse.scala.Terms$class.term(Terms.scala:38)
	at rsc.parse.scala.Parser.term(Parser.scala:13)
	at rsc.parse.scala.Defns$class.defnValOrVar(Defns.scala:163)
	at rsc.parse.scala.Defns$class.defnVal(Defns.scala:121)
	at rsc.parse.scala.Parser.defnVal(Parser.scala:13)
	at rsc.parse.scala.Terms$$anonfun$blockStats$1.apply(Terms.scala:502)
	at rsc.parse.scala.Terms$$anonfun$blockStats$1.apply(Terms.scala:447)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Terms$class.blockStats(Terms.scala:447)
	at rsc.parse.scala.Parser.blockStats(Parser.scala:13)
	at rsc.parse.scala.Terms$$anonfun$blockBraces$1.apply(Terms.scala:441)
	at rsc.parse.scala.Terms$$anonfun$blockBraces$1.apply(Terms.scala:437)
	at rsc.parse.scala.Helpers$class.inBraces(Helpers.scala:67)
	at rsc.parse.scala.Parser.inBraces(Parser.scala:13)
	at rsc.parse.scala.Terms$class.blockBraces(Terms.scala:436)
	at rsc.parse.scala.Terms$class.termArgs(Terms.scala:25)
	at rsc.parse.scala.Parser.termArgs(Parser.scala:13)
	at rsc.parse.scala.Terms$class.simpleTermRest(Terms.scala:343)
	at rsc.parse.scala.Terms$class.simpleTerm(Terms.scala:324)
	at rsc.parse.scala.Terms$class.prefixTerm(Terms.scala:239)
	at rsc.parse.scala.Terms$class.postfixTerm(Terms.scala:198)
	at rsc.parse.scala.Parser.postfixTerm(Parser.scala:13)
	at rsc.parse.scala.Terms$class.term1(Terms.scala:142)
	at rsc.parse.scala.Parser.term1(Parser.scala:13)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:134)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:92)
	at rsc.parse.scala.Helpers$class.inBraces(Helpers.scala:67)
	at rsc.parse.scala.Parser.inBraces(Parser.scala:13)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1.apply(Templates.scala:92)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1.apply(Templates.scala:89)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Templates$class.templateBraces(Templates.scala:89)
	at rsc.parse.scala.Templates$class.defnTemplate(Templates.scala:40)
	at rsc.parse.scala.Parser.defnTemplate(Parser.scala:13)
	at rsc.parse.scala.Defns$class.defnClass(Defns.scala:18)
	at rsc.parse.scala.Parser.defnClass(Parser.scala:13)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$packageStats$1.apply(Sources.scala:74)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$packageStats$1.apply(Sources.scala:53)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Sources$class.rsc$parse$scala$Sources$$packageStats(Sources.scala:53)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:48)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:18)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Sources$class.rsc$parse$scala$Sources$$sourceStats(Sources.scala:18)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:44)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:18)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Sources$class.rsc$parse$scala$Sources$$sourceStats(Sources.scala:18)
	at rsc.parse.scala.Sources$class.source(Sources.scala:15)
	at rsc.parse.scala.Parser.source(Parser.scala:13)
	at rsc.parse.scala.Parser.parse(Parser.scala:42)
	at rsc.Compiler$$anonfun$rsc$Compiler$$parse$1.apply(Compiler.scala:83)
	at rsc.Compiler$$anonfun$rsc$Compiler$$parse$1.apply(Compiler.scala:72)
	at scala.collection.immutable.List.flatMap(List.scala:338)
	at rsc.Compiler.rsc$Compiler$$parse(Compiler.scala:72)
	at rsc.Compiler$$anonfun$tasks$1.apply$mcV$sp(Compiler.scala:63)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:31)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:28)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:28)
	at spants.tasks.RscTask.run(RscTask.scala:56)
	at spants.sessions.Session$$anon$1.run(Session.scala:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xeno-by** [comment]
Here's a minimized reproduction:

```scala
class C {
  def x = """\"""
}
```

```
failed rsc: Test.scala:4: error: unclosed string literal

^
rsc.util.CrashException: unclosed string literal
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:10)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.scan.scala.Messages$class.reportOffset(Messages.scala:16)
	at rsc.scan.scala.Scanner.reportOffset(Scanner.scala:13)
	at rsc.scan.scala.Scanner.string(Scanner.scala:557)
	at rsc.scan.scala.Scanner.dispatchNormal(Scanner.scala:260)
	at rsc.scan.scala.Scanner.next(Scanner.scala:31)
	at rsc.parse.scala.Scanners$in$.nextToken(Scanners.scala:55)
	at rsc.parse.scala.Defns$class.defnDef(Defns.scala:61)
	at rsc.parse.scala.Parser.defnDef(Parser.scala:13)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:154)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1$$anonfun$apply$1.apply(Templates.scala:92)
	at rsc.parse.scala.Helpers$class.inBraces(Helpers.scala:67)
	at rsc.parse.scala.Parser.inBraces(Parser.scala:13)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1.apply(Templates.scala:92)
	at rsc.parse.scala.Templates$$anonfun$templateBraces$1.apply(Templates.scala:89)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Templates$class.templateBraces(Templates.scala:89)
	at rsc.parse.scala.Templates$class.defnTemplate(Templates.scala:45)
	at rsc.parse.scala.Parser.defnTemplate(Parser.scala:13)
	at rsc.parse.scala.Defns$class.defnClass(Defns.scala:18)
	at rsc.parse.scala.Parser.defnClass(Parser.scala:13)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$packageStats$1.apply(Sources.scala:74)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$packageStats$1.apply(Sources.scala:53)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Sources$class.rsc$parse$scala$Sources$$packageStats(Sources.scala:53)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:48)
	at rsc.parse.scala.Sources$$anonfun$rsc$parse$scala$Sources$$sourceStats$1.apply(Sources.scala:18)
	at rsc.parse.scala.Wildcards$class.banEscapingWildcards(Wildcards.scala:18)
	at rsc.parse.scala.Parser.banEscapingWildcards(Parser.scala:13)
	at rsc.parse.scala.Sources$class.rsc$parse$scala$Sources$$sourceStats(Sources.scala:18)
	at rsc.parse.scala.Sources$class.source(Sources.scala:15)
	at rsc.parse.scala.Parser.source(Parser.scala:13)
	at rsc.parse.scala.Parser.parse(Parser.scala:42)
	at rsc.checkparse.package$PathParseOps.parseRsc(package.scala:65)
	at rsc.checkparse.Main$.rscResult(Main.scala:25)
	at rsc.checkparse.Main$.rscResult(Main.scala:11)
	at rsc.checkbase.MainBase$$anonfun$process$1.apply(MainBase.scala:39)
	at rsc.checkbase.MainBase$$anonfun$process$1.apply(MainBase.scala:37)
	at scala.meta.internal.cli.Job$$anonfun$foreach$1.apply(Job.scala:14)
	at scala.meta.internal.cli.Job$$anonfun$foreach$1.apply(Job.scala:13)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.cli.Job.foreach(Job.scala:13)
	at rsc.checkbase.MainBase$class.process(MainBase.scala:37)
	at rsc.checkparse.Main$.process(Main.scala:11)
	at rsc.checkbase.MainBase$class.main(MainBase.scala:17)
	at rsc.checkparse.Main$.main(Main.scala:11)
	at rsc.checkparse.Main.main(Main.scala)
```
