### ISSUE TITLE
Reenable rsc/examples/semantic/src/main/scala/94.scala

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#306]
My fix to #305 seems to have regressed something in how symbols are created or assigned in 94.scala when it's outlined together with other semantic tests. I have no time to pursue this now, and our case study project seems to be unaffected, so I'll be leaving this for future work.

```
/Users/eburmako/Projects/rsc/examples/semantic/src/main/scala/94.scala:3: error: local1
class C {
^
rsc.util.CrashException: local1
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:10)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:18)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.scalasig.Pickle$HardlinkOps.sinfo$lzycompute(Pickle.scala:460)
	at rsc.scalasig.Pickle$HardlinkOps.sinfo(Pickle.scala:457)
	at rsc.scalasig.Pickle$HardlinkOps.isObject(Pickle.scala:469)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:77)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:74)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1099)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:74)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSym(Pickle.scala:37)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:258)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:250)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:249)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$7.apply(Pickle.scala:259)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$7.apply(Pickle.scala:259)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:259)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:250)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:249)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$apply$8.apply(Pickle.scala:296)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$apply$8.apply(Pickle.scala:294)
	at rsc.scalasig.Pickle$Stack$$anonfun$inExistentialType$2.apply(Pickle.scala:1126)
	at rsc.scalasig.Pickle$Stack$$anonfun$inExistentialType$2.apply(Pickle.scala:1126)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1099)
	at rsc.scalasig.Pickle$Stack.inExistentialType(Pickle.scala:1126)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:294)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:250)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:249)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSig(Pickle.scala:244)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:105)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:92)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:92)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:74)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1099)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:74)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitScope$4.apply(Pickle.scala:161)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitScope$4.apply(Pickle.scala:136)
	at scala.collection.immutable.List.map(List.scala:288)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitScope(Pickle.scala:136)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:201)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:171)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSig(Pickle.scala:170)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:105)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:92)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:92)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:74)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1099)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:74)
	at rsc.scalasig.Writer.write(Writer.scala:30)
	at rsc.Compiler.rsc$Compiler$$scalasig(Compiler.scala:165)
	at rsc.Compiler$$anonfun$phases$6.apply$mcV$sp(Compiler.scala:73)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:36)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:33)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:33)
	at rsc.checkbase.ToolUtil$$anonfun$rsc$1.apply(ToolUtil.scala:108)
	at rsc.checkbase.ToolUtil$$anonfun$rsc$1.apply(ToolUtil.scala:103)
	at scala.util.Either$RightProjection.flatMap(Either.scala:522)
	at rsc.checkbase.ToolUtil$class.rsc(ToolUtil.scala:103)
	at rsc.checkoutline.Main$.rsc(Main.scala:8)
	at rsc.checkoutline.Main$.rscResult(Main.scala:20)
	at rsc.checkoutline.Main$.rscResult(Main.scala:8)
	at rsc.checkbase.SimpleBase$class.rscResult(SimpleBase.scala:17)
	at rsc.checkoutline.Main$.rscResult(Main.scala:8)
	at rsc.checkoutline.Main$.rscResult(Main.scala:8)
	at rsc.checkbase.MainBase$$anonfun$process$1.apply(MainBase.scala:39)
	at rsc.checkbase.MainBase$$anonfun$process$1.apply(MainBase.scala:37)
	at scala.meta.internal.cli.Job$$anonfun$foreach$1.apply(Job.scala:14)
	at scala.meta.internal.cli.Job$$anonfun$foreach$1.apply(Job.scala:13)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.cli.Job.foreach(Job.scala:13)
	at rsc.checkbase.MainBase$class.process(MainBase.scala:37)
	at rsc.checkoutline.Main$.process(Main.scala:8)
	at rsc.tests.OutlineTests$$anonfun$3.apply(OutlineTests.scala:26)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
	at org.scalatest.FunSuite.run(FunSuite.scala:1560)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
	at sbt.ForkMain$Run$2.call(ForkMain.java:296)
	at sbt.ForkMain$Run$2.call(ForkMain.java:286)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
one problem found
[info] - outline for semantic *** FAILED ***
```

**Comment by xeno-by** [comment]
Thanks to https://github.com/twitter/rsc/pull/339, this is no longer an issue.
