### ISSUE TITLE
Spurious crash when pickling a complicated type

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#337]
```scala
class C {
  def m: M.D[T] forSome { type T <: Int } = ???
}

object M {
  class D[T]
}
```

```
Test.scala:1: error: local1
class C {
^
rsc.util.CrashException: local1
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:10)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.util.CrashUtil$class.crash(CrashUtil.scala:18)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.scalasig.Pickle$HardlinkOps.sinfo$lzycompute(Pickle.scala:557)
	at rsc.scalasig.Pickle$HardlinkOps.sinfo(Pickle.scala:554)
	at rsc.scalasig.Pickle$HardlinkOps.isObject(Pickle.scala:566)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:82)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:79)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1239)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:79)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSym(Pickle.scala:37)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:263)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:255)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:254)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$9.apply(Pickle.scala:264)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$9.apply(Pickle.scala:264)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:264)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:255)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:254)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$apply$8.apply(Pickle.scala:301)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1$$anonfun$apply$8.apply(Pickle.scala:299)
	at rsc.scalasig.Pickle$Stack$$anonfun$inExistentialType$2.apply(Pickle.scala:1266)
	at rsc.scalasig.Pickle$Stack$$anonfun$inExistentialType$2.apply(Pickle.scala:1266)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1239)
	at rsc.scalasig.Pickle$Stack.inExistentialType(Pickle.scala:1266)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:299)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitTpe$1.apply(Pickle.scala:255)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitTpe(Pickle.scala:254)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:232)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:176)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSig(Pickle.scala:175)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:110)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:97)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:97)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:79)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1239)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:79)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitScope$4.apply(Pickle.scala:166)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitScope$4.apply(Pickle.scala:141)
	at scala.collection.immutable.List.map(List.scala:288)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitScope(Pickle.scala:141)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:206)
	at rsc.scalasig.Pickle$$anonfun$rsc$scalasig$Pickle$$emitSig$1.apply(Pickle.scala:176)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle.rsc$scalasig$Pickle$$emitSig(Pickle.scala:175)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:110)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1$$anonfun$apply$3.apply(Pickle.scala:97)
	at rsc.scalasig.Entries.getOrElseUpdate(Entries.scala:27)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:97)
	at rsc.scalasig.Pickle$$anonfun$emitEmbeddedSym$1.apply(Pickle.scala:79)
	at rsc.scalasig.Pickle$Stack.inEmbedded(Pickle.scala:1239)
	at rsc.scalasig.Pickle.emitEmbeddedSym(Pickle.scala:79)
	at rsc.scalasig.Writer.write(Writer.scala:30)
	at rsc.Compiler.rsc$Compiler$$scalasig(Compiler.scala:165)
	at rsc.Compiler$$anonfun$phases$6.apply$mcV$sp(Compiler.scala:73)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:36)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:33)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:33)
	at rsc.cli.Main$.process(Main.scala:35)
	at rsc.cli.Main$.main(Main.scala:14)
	at rsc.cli.Main.main(Main.scala)
one error found
```

**Comment by xeno-by** [comment]
```
$ rsc -Xprint:outline Test.scala
Test.scala
==========
class <_empty_/C#><_empty_/C#`<init>`().> {
  def <_empty_/C#m().>: <_empty_/M.>.<_empty_/M.D#>[<local1>] forSome {type <local2> <: <scala/Int#>} = ???
}
object <_empty_/M.> {
  class <_empty_/M.D#>[<_empty_/M.D#[T]>]<_empty_/M.D#`<init>`().>
}
Source(List(DefnClass(Mods(List(ModClass())), TptId("C"), Nil, Some(PrimaryCtor(Mods(Nil), Nil)), Nil, Nil, None, List(DefnMethod(Mods(Nil), TermId("m"), Nil, Nil, Some(TptExistential(TptParameterize(TptSelect(TermId("M"), TptId("D")), List(TptId("T"))), List(DefnType(Mods(Nil), TptId("T"), Nil, None, Some(TptId("Int")), None)))), Some(TermId("???"))))), DefnObject(Mods(Nil), TermId("M"), Nil, Nil, None, List(DefnClass(Mods(List(ModClass())), TptId("D"), List(TypeParam(Mods(Nil), TptId("T"), Nil, None, None, Nil, Nil)), Some(PrimaryCtor(Mods(Nil), Nil)), Nil, Nil, None, Nil)))))
```
