### ISSUE TITLE
Non-static selections

### ISSUE THREAD

**Issue by xeno-by** [twitter/rsc#90]
```scala
class C {
  class X
}

object M {
  val c = new C
  def m: c.X = ???
}
```

```
Test.scala:7: error: compiler crash
  def m: c.X = ???
         ^
rsc.util.CrashException: val def <_empty_/M.c().> = new C()
DefnMethod(Mods(List(ModVal())), TermId("c"), Nil, Nil, None, Some(TermNew(Init(TptId("C"), Nil))))
	at rsc.util.CrashException$.apply(CrashException.scala:24)
	at rsc.util.ErrorUtil$class.crash(ErrorUtil.scala:18)
	at rsc.util.package$.crash(package.scala:5)
	at rsc.outline.Outliner.resolveScope(Outliner.scala:394)
	at rsc.outline.Outliner.loop$3(Outliner.scala:337)
	at rsc.outline.Outliner.apply(Outliner.scala:353)
	at rsc.outline.Outliner.rsc$outline$Outliner$$apply(Outliner.scala:254)
	at rsc.outline.Outliner.apply(Outliner.scala:232)
	at rsc.outline.Outliner.apply(Outliner.scala:19)
	at rsc.Compiler.rsc$Compiler$$outline(Compiler.scala:158)
	at rsc.Compiler$$anonfun$tasks$4.apply$mcV$sp(Compiler.scala:78)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:34)
	at rsc.Compiler$$anonfun$run$2.apply(Compiler.scala:31)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at rsc.Compiler.run(Compiler.scala:31)
	at rsc.cli.Main$.run(Main.scala:21)
	at rsc.cli.Main$.main(Main.scala:11)
	at rsc.cli.Main.main(Main.scala)
```

**Comment by xeno-by** [comment]
The hardest prerequisite for implementing this - unification of scoper and outliner - is already done. Now we just need to figure out https://github.com/scalameta/scalameta/issues/1649, and we'll be good to go.

**Comment by xeno-by** [comment]
Partially superseded by #98.

**Comment by xeno-by** [comment]
This actually work if we ascribe the return type of M.c. The crash happened not because non-static selections are unsupported, but because we can't select from something of unknown type. Also see https://github.com/twitter/rsc/issues/268.
